### PR TITLE
Fixed variety of bugs in both administrative panels

### LINKED ISSUE #125: Creation of users from system admin throws error

### PR DESCRIPTION
**Pull request by rushil-ambati**
Closes #125 and #126

### CODE REVIEW

**Comment by rushil-ambati** [comment]
Closes #133

**Comment by rushil-ambati** [comment]
Closes #134

File: entities/OfferType.php [hunk 1]
```diff
@@ -40,9 +40,9 @@ public function __construct($connection){
 	public function create(){
 
 		if(is_admin()){
-			$sql = "INSERT INTO offer_types ( name,category_id,default_text,active,created_by,updated_by) values (:type,:name,:category_id,:default_text,:active,:user_id,:user_id)";
+			$sql = "INSERT INTO offer_types ( name,category,category_id,default_text,active,created_by,updated_by) values (:name,:category_name,:category_id,:default_text,:active,:user_id,:user_id)";
```
Comment (mmillmor) [inline entities/OfferType.php:43]: We shouldn't be populating the category column. It shouldn't even exist any more. In production is is nullable, so I guess I didn't notice until now. We should remove the code populating it and drop the column

File: rest/offer_types.php [hunk 2]
```diff
@@ -17,13 +17,14 @@
...
     $offer_type->category_id = $data['category_id'];
+    // $offer_type->category_name = $data['category_name']; // This puts it in but isn't the same format as other records
     $offer_type->default_text = $data['default_text'];
     $offer_type->active = $data['active'];
 
     if(isset($data['id'])){
 		$offer_type->id=$data['id'];
 		$offer_type->update();
-		$offer_type->read();
+		//$offer_type->read();
```
Comment (mmillmor) [inline rest/offer_types.php:27]: Is there a reason for no longer reading it? Often we read after an update to get the values in the last_update_date and last_updated_by columns

File: rest/offer_types.php [hunk 3]
```diff
@@ -40,7 +41,7 @@
 		echo json_encode($offer_type_arr);*/
 			} else {
 				$offer_type->create();
-				$offer_type->read();
+				//$offer_type->read();
```
Comment (mmillmor) [inline rest/offer_types.php:44]: similarly we typically read after create to get those values

File: rest/user_organizations.php [hunk 4]
```diff
@@ -48,7 +48,7 @@
         }
 
     } else {
-	    $user_organization->user_id = $data['user_id'];
+	    // $user_organization->user_id = $data['user_id'];
```
Comment (mmillmor) [inline rest/user_organizations.php:51]: Why is setting the user_id commented out?

File: ui/src/js/viewModels/orgAdmin.js [hunk 5]
```diff
@@ -7,436 +7,444 @@
 /*
```
Comment (mmillmor) [inline ui/src/js/viewModels/orgAdmin.js:7]: The diffs in this file aren't showing up - it is telling me everything has changed. What has changed in reality?

File: ui/src/js/viewModels/orgAdmin.js [hunk 6]
```diff
@@ -7,436 +7,444 @@
...
+                        "client_share_approver": (self.userClientShareApprover().length > 0) ? "Y" : "N",
+                        "confirmed": (self.userConfirmed().length > 0) ? "Y" : "N"
+                    };
+                    return $.when(restClient.doPost('/rest/users', userData)
+                        .then(
+                            success = function (response) {
+                                self.postText("You have succesfully saved user details.");
+                                self.postTextColor("green");
+                                /*
+                                return $.when(restClient.doPost('/rest/organizations/' + self.userOrgId() + '/user_organizations', userOrgData)
```
Comment (mmillmor) [inline ui/src/js/viewModels/orgAdmin.js:309]: why is this commented out?

File: ui/src/js/viewModels/orgAdmin.js [hunk 7]
```diff
@@ -7,436 +7,444 @@
...
+                                    self.userOrgValues(response.user_organizations);
+                                    var userOrgs = self.userOrgValues().filter(function (user) {
+                                        user.adminTable = [];
+                                        if (user.admin === "Y") {
+                                            user.adminTable = ['checked'];
+                                        }
 
-                                        })
+                                    });
+                                    var promises = [];
```
Comment (mmillmor) [inline ui/src/js/viewModels/orgAdmin.js:375]: This was recently removed. Why was it added back?

File: entities/OfferType.php (hunk 1 above)
Comment (rushil-ambati) [reply entities/OfferType.php:43]: We weren't sure why it was not removed when the primary key was switched to the ID in the first place.
But sure, we'll remove the category column.

File: rest/offer_types.php (hunk 2 above)
Comment (rushil-ambati) [reply rest/offer_types.php:27]: The read was throwing errors along the lines of `Trying to access array offset on value of type bool in ...`

File: rest/offer_types.php (hunk 3 above)
Comment (rushil-ambati) [reply rest/offer_types.php:44]: This was also causing the errors `Trying to access array offset on value of type bool in ...`

File: rest/user_organizations.php (hunk 4 above)
Comment (rushil-ambati) [reply rest/user_organizations.php:51]: `could not read key 'user_id' from $data`

File: ui/src/js/viewModels/orgAdmin.js (hunk 5 above)
Comment (rushil-ambati) [reply ui/src/js/viewModels/orgAdmin.js:7]: We commented out
```
return $.when(restClient.doPost('/rest/organizations/' + self.userOrgId() + '/user_organizations', userOrgData)
    .then(
        success = function (response) {
            self.getUserOrgData(self.userOrgId());
            console.log("user data posted");
        })
);
```
Lines ~308-315

The reason it shows so many differences is because of the autoformatter in VSCode.

File: ui/src/js/viewModels/orgAdmin.js (hunk 6 above)
Comment (rushil-ambati) [reply ui/src/js/viewModels/orgAdmin.js:309]: Creating a user by calling `users` already calls `user_organizations` and creates a link as expected.
This manual call to `user_organizations` is redundant.

File: ui/src/js/viewModels/orgAdmin.js (hunk 7 above)
Comment (rushil-ambati) [reply ui/src/js/viewModels/orgAdmin.js:375]: Merge conflicts, we'll refactor this.
Why was it removed?

File: rest/offer_types.php (hunk 2 above)
Comment (mmillmor) [reply rest/offer_types.php:27]: sounds like we should be looking at why the read is a problem instead of commenting it out

File: rest/user_organizations.php (hunk 4 above)
Comment (mmillmor) [reply rest/user_organizations.php:51]: We're going to need the user_id though, or we can't create the row. It sounds like the problem is the code calling the service not setting it.

File: ui/src/js/viewModels/orgAdmin.js (hunk 7 above)
Comment (mmillmor) [reply ui/src/js/viewModels/orgAdmin.js:375]: It was there in the past to get the full user details to show on this screen, but now we navigate to the users screen instead, so we don't need the full user details here. Yes, we shoud re-remove it.

File: rest/offer_types.php (hunk 3 above)
Comment (mmillmor) [reply rest/offer_types.php:44]: Again, we should look at why read is causing a problem

**Comment by kiran-bahra** [comment]
We have successfully implemented DBS check into all required places. I have added it to this pull request as I don't know how to make a separate pull request for just the dbs check.
closes #16

File: ui/src/js/viewModels/orgAdmin.js (hunk 7 above)
Comment (kiran-bahra) [reply ui/src/js/viewModels/orgAdmin.js:384]: I tried removing the var promises = []; from my code, but it gave an error and the org admin page did not load.

> jQuery.Deferred exception: promises is not defined ReferenceError: promises is not defined
    at Object.<anonymous> (http://localhost/ui/web/js/viewModels/orgAdmin.js:386:41)
    at Function.each (http://localhost/ui/web/js/libs/jquery/jquery-3.5.1.js:381:19)
    at success (http://localhost/ui/web/js/viewModels/orgAdmin.js:385:39) undefined

that is the error I got in the console tab.
In the network tab, it shows that it did successfully load the user details.

File: ui/src/js/viewModels/orgAdmin.js [hunk 8]
```diff
@@ -7,436 +7,453 @@
...
-								"phone": null,
-								"admin":"N"
-                            };
+                    var userData =
+                    {
+                        "organization_id": self.userOrgId(),
+                        "user_name": self.userName(),
+                        "email": self.userEmail(),
+                        "phone": null,
+                        "admin": "Y"
```
[the remark this answers is not in the document]
Comment (kiran-bahra) [reply ui/src/js/viewModels/orgAdmin.js:206]: I think I accidentally left in a change from my testing. However, I'm not sure if you saw what I said about there being two saveUserButton functions, but this is part of the first of these functions. This saveUserFunction that starts on line 198 does not seem to have functionality since I tried commenting it out and as far I could tell nothing changed. Do you know why there are two saveUserButton functions, or shall we remove the one that isn't being used.

File: ui/src/js/viewModels/orgAdmin.js [hunk 9]
```diff
@@ -7,436 +7,453 @@
...
+                        "admin": (self.userAdmin().length > 0) ? "Y" : "N",
+                        "need_approver": (self.userNeedApprover().length > 0) ? "Y" : "N",
+                        "user_approver": (self.userApprover().length > 0) ? "Y" : "N",
+                        "manage_clients": (self.userManageClients().length > 0) ? "Y" : "N",
+                        "manage_offers": (self.userManageOffers().length > 0) ? "Y" : "N",
+                        "client_share_approver": (self.userClientShareApprover().length > 0) ? "Y" : "N",
+                        "dbs_check": (self.userDbsCheck()) ? "P" : "P",
+                        "confirmed": (self.userConfirmed().length > 0) ? "Y" : "N"
+                    };
+                    */
```
[the remark this answers is not in the document]
Comment (kiran-bahra) [reply ui/src/js/viewModels/orgAdmin.js:308]: This variable "userOrgData" used to be later on in the function, but that bit has since been commented out, so this variable wasn't being used at all, therefore I thought I would comment out this variable being declared since it isn't used. The function getUserOrgData is used instead of this variable.

File: ui/src/js/viewModels/user.js [hunk 10]
```diff
@@ -202,8 +204,15 @@ define(['appController','ojs/ojrouter','utils','ojs/ojcore', 'knockout', 'jquery
                                             console.log("User organizations not loaded");
                                             self.userOrgValid(false);
 
+                                        }).then(function () {
+                                            var dbsCheckStates = [
+                                                { value: 'Y', label: 'Yes' },
+                                                { value: 'N', label: 'No' },
+                                                { value: 'P', label: 'Pending' }
```
[the remark this answers is not in the document]
Comment (kiran-bahra) [reply ui/src/js/viewModels/user.js:211]: I will change it to be "Unknown", and the value in the table to "U" . We tried using null at first, but it caused some errors because of the way that the javascript treated null, and when we changed it to "P" these errors were no longer there, so we kept it with "P", but I can change it to "U" without any problems.

**Comment by kiran-bahra** [comment]
I have pushed a commit in which I changed all instances of dbs check from using "P" as the default to stand for Pending to using "U" as the default to stand for Unknown.
I have also fixed the value of admin on line 206 in orgAdmin.js I changed whilst testing back to its original value.

File: ui/src/js/viewModels/orgAdmin.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (mmillmor) [reply ui/src/js/viewModels/orgAdmin.js]: lYes, there is sometimes old code in there. If you are happy it is no longer required, delete it. I will likely ask in the review comments why, but please do realize that a question of why isn't the same as saying "don't do it".

File: entities/UserOrganization.php [hunk 11]
```diff
@@ -41,7 +42,11 @@ public function create(){
 			$uid=$_SESSION['id'];
 		}
 
-		if( $stmt->execute(['user_id'=>$this->user_id,'organization_id'=>$this->organization_id,'admin'=>$this->admin,'user_approver'=>$this->user_approver,'need_approver'=>$this->need_approver,'manage_offers'=>$this->manage_offers,'manage_clients'=>$this->manage_clients,'client_share_approver'=>$this->client_share_approver,'confirmed'=>$this->confirmed,'confirmation_string'=>$this->confirmation_string,'user_id2'=>$uid])){
+		if($this->admin=='N'){
```
Comment (mmillmor) [inline entities/UserOrganization.php:45]: I think this check is saying "if the user you are editing is not an admin, set dbs_check to U". It is looking at the user being edited, not the logged in user. The check should be if(!is_org_admin()|| $organization_id!=$_SESSION['organization_id'])

File: ui/src/js/viewModels/orgAdmin.js [hunk 12]
```diff
@@ -7,436 +7,453 @@
...
+                        "id": self.id(),
+                        "user_id": self.userId(),
+                        "organization_id": self.userOrgId(),
+                        "admin": (self.userAdmin().length > 0) ? "Y" : "N",
+                        "need_approver": (self.userNeedApprover().length > 0) ? "Y" : "N",
+                        "user_approver": (self.userApprover().length > 0) ? "Y" : "N",
+                        "manage_clients": (self.userManageClients().length > 0) ? "Y" : "N",
+                        "manage_offers": (self.userManageOffers().length > 0) ? "Y" : "N",
+                        "client_share_approver": (self.userClientShareApprover().length > 0) ? "Y" : "N",
+                        "dbs_check": (self.userDbsCheck()) ? "U" : "U",
```
Comment (mmillmor) [inline ui/src/js/viewModels/orgAdmin.js:305]: This looks odd- we are checking if self.userDbsCheck() is true, and if it is, we set dbs_check to U. If it is not, we also set it to U.

File: entities/UserOrganization.php (hunk 11 above)
Comment (kiran-bahra) [reply entities/UserOrganization.php]: I have changed the check to what you suggested, and also added an if(!is_admin) check to this check and another check we implemented to ensure that system admins can edit dbs check even if they aren't an org admin for that org.

File: ui/src/js/viewModels/orgAdmin.js (hunk 12 above)
Comment (kiran-bahra) [reply ui/src/js/viewModels/orgAdmin.js]: I have changed it to the check we use in user.js although as this is part of the commented out section it doesn't affect the code.

File: ui/src/js/viewModels/orgAdmin.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (kiran-bahra) [reply ui/src/js/viewModels/orgAdmin.js]: I have deleted the unused function - I have fully tested the org admin tab and everything still works (besides from a couple of bugs we already knew about).

File: rest/user_organizations.php (hunk 4 above)
Comment (kiran-bahra) [reply rest/user_organizations.php:52]: I have un-commented this line and it didn't cause any errors when creating or editing users so I don't think it is causing an error any more.

File: rest/offer_types.php (hunk 2 above)
Comment (kiran-bahra) [reply rest/offer_types.php:27]: I un-commented this and it didn't throw any errors so I don't think it is throwing an error anymore.

File: rest/offer_types.php (hunk 3 above)
Comment (kiran-bahra) [reply rest/offer_types.php:44]: I un-commented this and it didn't throw any errors so I don't think it is throwing an error anymore.

**Comment by kiran-bahra** [comment]
I have pushed a commit in which I un-commented three of the lines which we originally commented because they were throwing errors but they aren't any more. These lines are 27 & 44 in offer_types.php and 51 in user_organizations.php

**Comment by kiran-bahra** [comment]
So the only issues we have left in this pull request (assuming my commits today do not contain any further issues) are the var promises[] and the removal of category from offer types.

**Comment by kiran-bahra** [comment]
@mmillmor We have successfully removed the "category" column from the offer_types table and everywhere that used it has been changed to use the "name" column in type_categories.
The column can be deleted from the database now, but I am unsure about how that works, so if you can sort that out that would be great.
